new Stat("Dexterity")
new Stat("Strength", "\nYour pure muscle performance.\nHow high can you throw?\nHow hard can you punsh?")
new Stat("Constitution")
new Stat("Speed")
new Stat("Perception")
new Stat("Charisma")
new Stat("Intelligence")
new Stat("Luck", "\nTen times tails in a row? No, I'm not cheating, I just have a high Luck stat!")
new Stat("Soul")